services:
  extractor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scholar-extractor
    env_file:
      - .env
    ports:
      - "${API_PORT:-8002}:8002"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8002
      - DEBUG=${DEBUG:-False}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - RABBITMQ_HOST=user-rabbitmq
      - RABBITMQ_PORT=5672
      - GROBID_URL=http://pdf_extractor_grobid:8070
      - REDIS_URL=redis://user-redis:6379/0
      - HF_HOME=/app/cache/huggingface
      - TORCH_HOME=/app/cache/torch
      - EASYOCR_MODULE_PATH=/app/cache/easyocr
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - VECLIB_MAXIMUM_THREADS=1
      - BLAS_NUM_THREADS=1
      - LAPACK_NUM_THREADS=1
      - TORCH_NUM_THREADS=1
      - TORCH_NUM_INTEROP_THREADS=1
    volumes:
      - ./paper:/app/paper
      - ./logs:/app/logs
      - ./cache:/app/cache
      - ./uploads:/app/uploads
    networks:
      - scholarai-network
    restart: unless-stopped

    # —— Resource controls (Compose) ——
    # Use ONE style only. Here we use NanoCPUs (cpus) + memory limits.
    cpus: 2.0                 # caps to ~2 cores
    cpu_shares: 1024          # relative weight vs other containers
    mem_limit: 4g             # hard memory cap
    mem_reservation: 1g       # soft reservation

    # ulimits are fine
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  scholarai-network:
    external: true
    name: docker_scholarai-network
