rules:
- action: increase_table_validation_threshold
  condition: metrics.get('table_false_positive_rate', 0) > 0.4
  description: Increase table validation threshold when false positive rate is high
  enabled: true
  name: high_table_fp_rate
  priority: 10
- action: enable_ocr_fallback
  condition: metrics.get('text_coherence', 1) < 0.5
  description: Enable OCR fallback when text coherence is low
  enabled: true
  name: low_text_coherence
  priority: 8
- action: disable_cv_detection
  condition: metrics.get('average_processing_time', 0) > 300
  description: Disable CV detection when processing is slow
  enabled: true
  name: slow_processing
  priority: 6
- action: enable_error_recovery
  condition: metrics.get('success_rate', 1) < 0.8
  description: Enable enhanced error recovery when success rate is low
  enabled: true
  name: low_success_rate
  priority: 9
- action: optimize_for_speed
  condition: metrics.get('average_quality', 0) > 0.85 and metrics.get('success_rate',
    0) > 0.9
  description: Optimize for speed when quality and success rate are high
  enabled: true
  name: high_quality_performance
  priority: 4
- action: reduce_parallel_processing
  condition: metrics.get('memory_usage', 0) > 3000
  description: Reduce parallel processing under memory pressure
  enabled: true
  name: memory_pressure
  priority: 7
